# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TalkGenius' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Networking
  pod 'Alamofire', '~> 5.8'

  # JSON Parsing
  pod 'SwiftyJSON', '~> 5.0'

  # Keychain Storage
  pod 'KeychainAccess', '~> 4.2'

  # UI
  pod 'SnapKit', '~> 5.6'

  target 'TalkGeniusTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TalkGeniusUITests' do
    # Pods for testing
  end

end

target 'TalkGeniusKeyboard' do
  use_frameworks!

  # Shared networking and storage for keyboard extension
  pod 'Alamofire', '~> 5.8'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'KeychainAccess', '~> 4.2'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
